import UIKit

class ViewController: UIViewController {
    @IBOutlet weak var textView: UITextView!

    @IBAction func convertHankaku(_ sender: Any) {
        textView.text = convert(target: textView.text)
    }

    @IBAction func pasteCopied(_ sender: Any) {
        let pasteBoard = UIPasteboard.general

        if let data: Data = pasteBoard.data(forPasteboardType: "public.text"),
            let str = String(data: data, encoding: .utf8),
            let text = textView.text {
            textView.text = text + str
        }
    }

    @IBAction func copyWord(_ sender: Any) {
        let pasteBoard = UIPasteboard.general

        if let data: Data = textView.text.data(using: .utf8) {
            pasteBoard.setData(data, forPasteboardType: "public.text")
        }
    }

    // swiftlint:disable function_body_length
    private func convert(target: String) -> String {
        var converted: String = target
        converted = converted.replacingOccurrences(of: "ヴ", with: "ｳﾞ")
        converted = converted.replacingOccurrences(of: "ョ", with: "ｮ")
        converted = converted.replacingOccurrences(of: "ュ", with: "ｭ")
        converted = converted.replacingOccurrences(of: "ャ", with: "ｬ")
        converted = converted.replacingOccurrences(of: "ッ", with: "ｯ")
        converted = converted.replacingOccurrences(of: "ォ", with: "ｫ")
        converted = converted.replacingOccurrences(of: "ェ", with: "ｪ")
        converted = converted.replacingOccurrences(of: "ゥ", with: "ｩ")
        converted = converted.replacingOccurrences(of: "ィ", with: "ｨ")
        converted = converted.replacingOccurrences(of: "ァ", with: "ｧ")
        converted = converted.replacingOccurrences(of: "ポ", with: "ﾎﾟ")
        converted = converted.replacingOccurrences(of: "ペ", with: "ﾍﾟ")
        converted = converted.replacingOccurrences(of: "プ", with: "ﾌﾟ")
        converted = converted.replacingOccurrences(of: "ピ", with: "ﾋﾟ")
        converted = converted.replacingOccurrences(of: "パ", with: "ﾊﾟ")
        converted = converted.replacingOccurrences(of: "ボ", with: "ﾎﾞ")
        converted = converted.replacingOccurrences(of: "ベ", with: "ﾍﾞ")
        converted = converted.replacingOccurrences(of: "ブ", with: "ﾌﾞ")
        converted = converted.replacingOccurrences(of: "ビ", with: "ﾋﾞ")
        converted = converted.replacingOccurrences(of: "バ", with: "ﾊﾞ")
        converted = converted.replacingOccurrences(of: "ド", with: "ﾄﾞ")
        converted = converted.replacingOccurrences(of: "デ", with: "ﾃﾞ")
        converted = converted.replacingOccurrences(of: "ズ", with: "ﾂﾞ")
        converted = converted.replacingOccurrences(of: "ヂ", with: "ﾁﾞ")
        converted = converted.replacingOccurrences(of: "ダ", with: "ﾀﾞ")
        converted = converted.replacingOccurrences(of: "ゾ", with: "ｿﾞ")
        converted = converted.replacingOccurrences(of: "ゼ", with: "ｾﾞ")
        converted = converted.replacingOccurrences(of: "ズ", with: "ｽﾞ")
        converted = converted.replacingOccurrences(of: "ジ", with: "ｼﾞ")
        converted = converted.replacingOccurrences(of: "ザ", with: "ｻﾞ")
        converted = converted.replacingOccurrences(of: "ゴ", with: "ｺﾞ")
        converted = converted.replacingOccurrences(of: "ゲ", with: "ｹﾞ")
        converted = converted.replacingOccurrences(of: "グ", with: "ｸﾞ")
        converted = converted.replacingOccurrences(of: "ギ", with: "ｷﾞ")
        converted = converted.replacingOccurrences(of: "ガ", with: "ｶﾞ")
        converted = converted.replacingOccurrences(of: "ン", with: "ﾝ")
        converted = converted.replacingOccurrences(of: "ヲ", with: "ｦ")
        converted = converted.replacingOccurrences(of: "ワ", with: "ﾜ")
        converted = converted.replacingOccurrences(of: "ロ", with: "ﾛ")
        converted = converted.replacingOccurrences(of: "レ", with: "ﾚ")
        converted = converted.replacingOccurrences(of: "ル", with: "ﾙ")
        converted = converted.replacingOccurrences(of: "リ", with: "ﾘ")
        converted = converted.replacingOccurrences(of: "ラ", with: "ﾗ")
        converted = converted.replacingOccurrences(of: "ヨ", with: "ﾖ")
        converted = converted.replacingOccurrences(of: "ユ", with: "ﾕ")
        converted = converted.replacingOccurrences(of: "ヤ", with: "ﾔ")
        converted = converted.replacingOccurrences(of: "モ", with: "ﾓ")
        converted = converted.replacingOccurrences(of: "メ", with: "ﾒ")
        converted = converted.replacingOccurrences(of: "ム", with: "ﾑ")
        converted = converted.replacingOccurrences(of: "ミ", with: "ﾐ")
        converted = converted.replacingOccurrences(of: "マ", with: "ﾏ")
        converted = converted.replacingOccurrences(of: "ホ", with: "ﾎ")
        converted = converted.replacingOccurrences(of: "ヘ", with: "ﾍ")
        converted = converted.replacingOccurrences(of: "フ", with: "ﾌ")
        converted = converted.replacingOccurrences(of: "ヒ", with: "ﾋ")
        converted = converted.replacingOccurrences(of: "ハ", with: "ﾊ")
        converted = converted.replacingOccurrences(of: "ノ", with: "ﾉ")
        converted = converted.replacingOccurrences(of: "ネ", with: "ﾈ")
        converted = converted.replacingOccurrences(of: "ヌ", with: "ﾇ")
        converted = converted.replacingOccurrences(of: "ニ", with: "ﾆ")
        converted = converted.replacingOccurrences(of: "ナ", with: "ﾅ")
        converted = converted.replacingOccurrences(of: "ト", with: "ﾄ")
        converted = converted.replacingOccurrences(of: "テ", with: "ﾃ")
        converted = converted.replacingOccurrences(of: "ツ", with: "ﾂ")
        converted = converted.replacingOccurrences(of: "チ", with: "ﾁ")
        converted = converted.replacingOccurrences(of: "タ", with: "ﾀ")
        converted = converted.replacingOccurrences(of: "ソ", with: "ｿ")
        converted = converted.replacingOccurrences(of: "セ", with: "ｾ")
        converted = converted.replacingOccurrences(of: "ス", with: "ｽ")
        converted = converted.replacingOccurrences(of: "シ", with: "ｼ")
        converted = converted.replacingOccurrences(of: "サ", with: "ｻ")
        converted = converted.replacingOccurrences(of: "コ", with: "ｺ")
        converted = converted.replacingOccurrences(of: "ケ", with: "ｹ")
        converted = converted.replacingOccurrences(of: "ク", with: "ｸ")
        converted = converted.replacingOccurrences(of: "キ", with: "ｷ")
        converted = converted.replacingOccurrences(of: "カ", with: "ｶ")
        converted = converted.replacingOccurrences(of: "オ", with: "ｵ")
        converted = converted.replacingOccurrences(of: "エ", with: "ｴ")
        converted = converted.replacingOccurrences(of: "ウ", with: "ｳ")
        converted = converted.replacingOccurrences(of: "イ", with: "ｲ")
        converted = converted.replacingOccurrences(of: "ア", with: "ｱ")
        converted = converted.replacingOccurrences(of: "ゔ", with: "ｳﾞ")
        converted = converted.replacingOccurrences(of: "ょ", with: "ｮ")
        converted = converted.replacingOccurrences(of: "ゅ", with: "ｭ")
        converted = converted.replacingOccurrences(of: "ゃ", with: "ｬ")
        converted = converted.replacingOccurrences(of: "っ", with: "ｯ")
        converted = converted.replacingOccurrences(of: "ぉ", with: "ｫ")
        converted = converted.replacingOccurrences(of: "ぇ", with: "ｪ")
        converted = converted.replacingOccurrences(of: "ぅ", with: "ｩ")
        converted = converted.replacingOccurrences(of: "ぃ", with: "ｨ")
        converted = converted.replacingOccurrences(of: "ぁ", with: "ｧ")
        converted = converted.replacingOccurrences(of: "ぽ", with: "ﾎﾟ")
        converted = converted.replacingOccurrences(of: "ぺ", with: "ﾍﾟ")
        converted = converted.replacingOccurrences(of: "ぷ", with: "ﾌﾟ")
        converted = converted.replacingOccurrences(of: "ぴ", with: "ﾋﾟ")
        converted = converted.replacingOccurrences(of: "ぱ", with: "ﾊﾟ")
        converted = converted.replacingOccurrences(of: "ぼ", with: "ﾎﾞ")
        converted = converted.replacingOccurrences(of: "べ", with: "ﾍﾞ")
        converted = converted.replacingOccurrences(of: "ぶ", with: "ﾌﾞ")
        converted = converted.replacingOccurrences(of: "び", with: "ﾋﾞ")
        converted = converted.replacingOccurrences(of: "ば", with: "ﾊﾞ")
        converted = converted.replacingOccurrences(of: "ど", with: "ﾄﾞ")
        converted = converted.replacingOccurrences(of: "で", with: "ﾃﾞ")
        converted = converted.replacingOccurrences(of: "づ", with: "ﾂﾞ")
        converted = converted.replacingOccurrences(of: "ぢ", with: "ﾁﾞ")
        converted = converted.replacingOccurrences(of: "だ", with: "ﾀﾞ")
        converted = converted.replacingOccurrences(of: "ぞ", with: "ｿﾞ")
        converted = converted.replacingOccurrences(of: "ぜ", with: "ｾﾞ")
        converted = converted.replacingOccurrences(of: "ず", with: "ｽﾞ")
        converted = converted.replacingOccurrences(of: "じ", with: "ｼﾞ")
        converted = converted.replacingOccurrences(of: "ざ", with: "ｻﾞ")
        converted = converted.replacingOccurrences(of: "ご", with: "ｺﾞ")
        converted = converted.replacingOccurrences(of: "げ", with: "ｹﾞ")
        converted = converted.replacingOccurrences(of: "ぐ", with: "ｸﾞ")
        converted = converted.replacingOccurrences(of: "ぎ", with: "ｷﾞ")
        converted = converted.replacingOccurrences(of: "が", with: "ｶﾞ")
        converted = converted.replacingOccurrences(of: "ん", with: "ﾝ")
        converted = converted.replacingOccurrences(of: "を", with: "ｦ")
        converted = converted.replacingOccurrences(of: "わ", with: "ﾜ")
        converted = converted.replacingOccurrences(of: "ろ", with: "ﾛ")
        converted = converted.replacingOccurrences(of: "れ", with: "ﾚ")
        converted = converted.replacingOccurrences(of: "る", with: "ﾙ")
        converted = converted.replacingOccurrences(of: "り", with: "ﾘ")
        converted = converted.replacingOccurrences(of: "ら", with: "ﾗ")
        converted = converted.replacingOccurrences(of: "よ", with: "ﾖ")
        converted = converted.replacingOccurrences(of: "ゆ", with: "ﾕ")
        converted = converted.replacingOccurrences(of: "や", with: "ﾔ")
        converted = converted.replacingOccurrences(of: "も", with: "ﾓ")
        converted = converted.replacingOccurrences(of: "め", with: "ﾒ")
        converted = converted.replacingOccurrences(of: "む", with: "ﾑ")
        converted = converted.replacingOccurrences(of: "み", with: "ﾐ")
        converted = converted.replacingOccurrences(of: "ま", with: "ﾏ")
        converted = converted.replacingOccurrences(of: "ほ", with: "ﾎ")
        converted = converted.replacingOccurrences(of: "へ", with: "ﾍ")
        converted = converted.replacingOccurrences(of: "ふ", with: "ﾌ")
        converted = converted.replacingOccurrences(of: "ひ", with: "ﾋ")
        converted = converted.replacingOccurrences(of: "は", with: "ﾊ")
        converted = converted.replacingOccurrences(of: "の", with: "ﾉ")
        converted = converted.replacingOccurrences(of: "ね", with: "ﾈ")
        converted = converted.replacingOccurrences(of: "ぬ", with: "ﾇ")
        converted = converted.replacingOccurrences(of: "に", with: "ﾆ")
        converted = converted.replacingOccurrences(of: "な", with: "ﾅ")
        converted = converted.replacingOccurrences(of: "と", with: "ﾄ")
        converted = converted.replacingOccurrences(of: "て", with: "ﾃ")
        converted = converted.replacingOccurrences(of: "つ", with: "ﾂ")
        converted = converted.replacingOccurrences(of: "ち", with: "ﾁ")
        converted = converted.replacingOccurrences(of: "た", with: "ﾀ")
        converted = converted.replacingOccurrences(of: "そ", with: "ｿ")
        converted = converted.replacingOccurrences(of: "せ", with: "ｾ")
        converted = converted.replacingOccurrences(of: "す", with: "ｽ")
        converted = converted.replacingOccurrences(of: "し", with: "ｼ")
        converted = converted.replacingOccurrences(of: "さ", with: "ｻ")
        converted = converted.replacingOccurrences(of: "こ", with: "ｺ")
        converted = converted.replacingOccurrences(of: "け", with: "ｹ")
        converted = converted.replacingOccurrences(of: "く", with: "ｸ")
        converted = converted.replacingOccurrences(of: "き", with: "ｷ")
        converted = converted.replacingOccurrences(of: "か", with: "ｶ")
        converted = converted.replacingOccurrences(of: "お", with: "ｵ")
        converted = converted.replacingOccurrences(of: "え", with: "ｴ")
        converted = converted.replacingOccurrences(of: "う", with: "ｳ")
        converted = converted.replacingOccurrences(of: "い", with: "ｲ")
        converted = converted.replacingOccurrences(of: "あ", with: "ｱ")
        return converted
    }

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}
